src/app/blogger/urls.py
from django.urls import path
from . import views

app_name = 'blogger'
urlpatterns = [
    path('', views.BloggerView.as_view(), name='index'),
]

src/app/contact/urls.py
from django.urls import path

from . import views

app_name = 'contact'

urlpatterns = [
    path('', views.ContactFormView.as_view()),
    path('index', views.ContactFormView.as_view(), name='index'),
    path('successful', views.get_successful_page, name='successful'),
    path('unsuccessful', views.get_unsuccessful_page, name='unsuccessful'),
]

src/app/home/urls.py
from django.urls import path

from . import views

app_name = 'home'
urlpatterns = [
    path('', views.get_home_page, name='index'),
]

src/app/main/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('home/', include('home.urls', namespace='home')),
    path('blogger/', include('blogger.urls', namespace='blogger')),
    path('contact/', include('contact.urls', namespace='contact')),
]

src/app/blogger/models.py
from django.db import models

# Create your models here.

class BlogPost(models.Model):
    title = models.CharField(max_length=50)
    content = models.CharField(max_length=3000)
    date_time = models.DateTimeField()

src/app/contact/models.py
from django.db import models

# Create your models here.

src/app/home/models.py
from django.db import models

# Create your models here.

src/app/contact/forms.py
from django import forms

class ContactForm(forms.Form):
    name = forms.CharField(label='name', max_length=100, widget=forms.TextInput(attrs={'class': "form-control"}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': "form-control"}))
    phone_number = forms.IntegerField(widget=forms.NumberInput(attrs={'class': "form-control"}))

src/app/blogger/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.template import loader
from django.views import generic
from .models import BlogPost

# Create your views here.

class BloggerView(generic.TemplateView):
    template_name = 'blogger/index.html'

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        # Add in a QuerySet of all the books
        context['blog_posts'] = BlogPost.objects.all()
        return context

src/app/contact/views.py
from django.shortcuts import render
from django.template import loader
from django.http import HttpResponse
from django.views import generic
from .forms import ContactForm

# Create your views here.

def get_successful_page(request):
    template = loader.get_template('contact/successful.html')
    return HttpResponse(template.render())


def get_unsuccessful_page(request):
    template = loader.get_template('contact/unsuccessful.html')
    return HttpResponse(template.render())


class ContactFormView(generic.FormView):
    template_name = 'contact/index.html'
    form_class = ContactForm
    success_url = '/contact/successful'

    def form_valid(self, form):
        # This method is called when valid form data has been POSTed.
        # It should return an HttpResponse.
        return super().form_valid(form)

src/app/home/views.py
from django.shortcuts import render
from django.template import loader
from django.http import HttpResponse

# Create your views here.


def get_home_page(request):
    template = loader.get_template('home/index.html')
    return HttpResponse(template.render())

src/app/blogger/templates/blogger/index.html
{% extends 'main/base.html' %}

{% load static %}

{% block content %}

<link rel="stylesheet" href="{% static 'blogger/blogger.css' %}">

<div class="blogger-container container-fluid">
  <div class="blogger-container-header">
    <h2>Personal Blog</h2>
  </div>

  <br>
  <hr>
  <br>

  {% for blog in blog_posts %}
    <div class="blogpost">
      <h5><strong>{{ blog.title }}</strong></h5>
      <p>{{ blog.content }}</p>
      <label class="blogpost-datetime" for="blogpost">{{ blog.date_time }}</label>
    </div>
    <br>
  {% endfor %}

</div>

{% endblock %}

src/app/contact/templates/contact/index.html
{% extends 'main/base.html' %}

{% load static %}

{% block content %}

<link rel="stylesheet" href="{% static 'contact/contact.css' %}">

<div class="contact-container container-fluid">
  <div class="contact-container-header">
    <h2>Contact Me...</h2>
  </div>

  <br>
  <hr>
  <br>

  <form action="/contact/index" method="post">
    {% csrf_token %}
    {{ form }}

    <br>
    <hr>
    <br>
    <input type="submit" value="Submit" class="btn btn-primary">
  </form>

</div>

{% endblock %}

src/app/contact/templates/contact/successful.html
{% extends 'main/base.html' %}

{% load static %}

{% block content %}

<link rel="stylesheet" href="{% static 'contact/contact.css' %}">

<div class="successful-contact container-fluid">
  <h2>Submission Successful! Thank you for contacting me. I will reach back out to you at the earliest...</h2>
</div>

{% endblock %}

src/app/contact/templates/contact/unsuccessful.html
{% extends 'main/base.html' %}

{% load static %}

{% block content %}

<link rel="stylesheet" href="{% static 'contact/contact.css' %}">

<div class="unsuccessful-contact container-fluid">
  <h2>Submission Unsuccessful! Please try again, or feel free to reach me via one of the following methods...</h2>
  <h4>Phone: 123-456-7890</h4>
  <h4>Email: blogSiteAdmin@blogsite.com</h4>
</div>

{% endblock %}

src/app/home/templates/home/index.html
{% extends 'main/base.html' %}

{% load static %}

{% block content %}

<link rel="stylesheet" href="{% static 'home/home.css' %}">

<div class="home-container container-fluid">
  <div class="home-container-header">
    <h2>Welcome to my personal blog!</h2>
  </div>

  <br>
  <hr>
  <br>

  <div class="row intro">
    <div class="col-12">
      <p>E in quis quamquam, doctrina ubi fugiat et malis pariatur te adipisicing, nam elit mandaremus iis te
        legam aliqua sed nescius, deserunt a nescius, ne qui malis proident, malis deserunt appellat.
        Probant elit eu mentitum transferrem de quamquam illum culpa e fugiat. Eiusmod quem eiusmod offendit
        est ad sed labore incurreret.Nulla incididunt iudicem hic tamen sed te magna excepteur, arbitror
        sint qui doctrina illustriora non aliqua ubi nostrud eu esse ne ex veniam irure et quibusdam hic
        fugiat ullamco quo vidisse ex ita legam doctrina, laboris labore deserunt mandaremus. Si quorum
        laborum possumus. De cernantur despicationes, summis laboris consectetur, vidisse et summis
        senserit, ipsum incurreret expetendis. Eu cillum ingeniis coniunctione, dolore exquisitaque pariatur
        legam iudicem eu multos an ita dolore aliquip ex cupidatat firmissimum de incurreret, eu noster fore
        non pariatur, iis nisi mentitum a te dolor enim ex doctrina se probant dolore dolor nostrud minim.</p>
    </div>
  </div>

  <br>
  <hr>
  <br>

  <div class="row gallery">
    <div class="col-4">
      <img class="img-fluid" src="{% static 'home/images/blog_home_pic1.jpeg' %}" alt="pic_1">
    </div>
    <div class="col-4">
      <img class="img-fluid" src="{% static 'home/images/blog_home_pic2.jpeg' %}" alt="pic_2">
    </div>
    <div class="col-4">
      <img class="img-fluid" src="{% static 'home/images/blog_home_pic3.jpeg' %}" alt="pic_3">
    </div>
  </div>

</div>

{% endblock %}

src/app/main/templates/main/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr" style="position:relative; height:100%; width:100%;">
  <head>
    <meta charset="utf-8">
    <title>Blogger Application</title>
  </head>
  <body style="height:100%; width:100%;">

    {# Load the tag library #}
    {% load bootstrap4 %}

    {# Load CSS and JavaScript #}
    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}

    {# Display django.contrib.messages as Bootstrap alerts #}
    {% bootstrap_messages %}

    {% load static %}

    <link rel="stylesheet" href="{% static 'main/base.css' %}">

    <div class="container-fluid" style="min-height:100%; height:100%; min-width: 100%; width:100%; padding: 0%;">
      <div class="row no-gutters" style="min-height:100%; height: 100%; width:100%;">

        <div class="col-2 side-navbar" style="min-height:100%;">
          {% include 'main/partials/_nav.html' %}
        </div>

        <div class="col-10 main-content">
          <div class="main-content-container">
            {% block content %} {% endblock %}
          </div>

          {% include 'main/partials/_footer.html' %}
        </div>

      </div>
    </div>

  </body>
</html>

src/app/main/templates/main/partials/_footer.html
<div class="footer text-center main-content-footer">
  <!-- Copyright -->
  <div class="text-center p-3">
    © Le_Blog 2021, v1.0.0
  </div>
  <!-- Copyright -->
</div>

src/app/main/templates/main/partials/_nav.html
<div class="navbar-nav">
  <div class="container-fluid">
    <div class="row">
      <div class="col-12">
        <div class="nav-title">
          <h2>My Personal Blog</h2>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-12">
        <h3><a class="nav-item nav-link active" href="{% url 'home:index' %}">Home <span class="sr-only">(current)</span></a></h3>
      </div>
    </div>
    <div class="row">
      <div class="col-12">
        <h3><a class="nav-item nav-link" href="{% url 'blogger:index' %}">Blog</a></h3>
      </div>
    </div>
    <div class="row">
      <div class="col-12">
        <h3><a class="nav-item nav-link" href="{% url 'contact:index' %}">Contact</a></h3>
      </div>
    </div>
  </div>
</div>